### ISSUE TITLE
Spring boot actuator management port not working as expected

### ISSUE THREAD

**Issue by hefberk** [evernat/grails-melody-plugin#73]
Grails version : 3.3.0

**build.gradle**
```gradle
compile('org.grails.plugins:grails-melody-plugin:1.70.0') {
        exclude group: 'net.bull.javamelody', module: 'javamelody-core'
    }
compile 'net.bull.javamelody:javamelody-core:1.83.0'
provided "org.springframework.boot:spring-boot-starter-actuator"
```

**application.groovy** 
```groovy
 server.port=8080
 management.port=8088
 management.security.enabled=false
 management.ssl.enabled=false
 javamelody.log=true
```

**application.yml**
```yml
endpoints:
    enabled: true
    jmx:
        enabled: true
        unique-names: true
javamelody:
    sql-transform-pattern: \d+
    jmx-expose-enabled: true
    management-endpoint-monitoring-enabled: true
    monitoring-path: "/actuator/monitoring"
management:
    endpoints:
        web:
            exposure:
                include: "*"
    context-path: "/actuator"
```

try with and without context-path and monitoring path, the /monitoring endpoint works as expected but is always served on 8080 port...
The actuator is actually working as expected too.
Any help ?
